//HintName: GroupingConfigRegistrations.g.cs
// <auto-generated/>
#nullable enable

namespace Microsoft.Extensions.DependencyInjection;

[global::System.CodeDom.Compiler.GeneratedCode("Community.HotChocolate.Data.Grouping.Analyzers", "{ScrubbedVersion}")]
public static class GroupingConfigRegistrations
{
    /// <summary>
    /// Registers every <c>GroupingConfig&lt;T&gt;</c> subclass discovered in the
    /// current assembly. Generated by Community.HotChocolate.Data.Grouping.Analyzers.
    /// </summary>
    public static global::HotChocolate.Execution.Configuration.IRequestExecutorBuilder AddGroupingConfigs(
        this global::HotChocolate.Execution.Configuration.IRequestExecutorBuilder builder)
    {
        global::HotChocolate.Data.Grouping.GroupingSchemaBuilderExtensions.AddGroupingConfig<global::App.EmployeeGroupingConfig>(builder);
        return builder;
    }
}
