name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - ".github/workflows/gh-pages.yml"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - ".github/workflows/gh-pages.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Test
        run: dotnet test -c Release
